// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBgMNq0nWF7YUpVSEmxTTGi7ZQnMJDUQ',
    appId: '1:449046493777:web:cc45b551d6a49a5238d670',
    messagingSenderId: '449046493777',
    projectId: 'gestao-software-e052f',
    authDomain: 'gestao-software-e052f.firebaseapp.com',
    storageBucket: 'gestao-software-e052f.firebasestorage.app',
    measurementId: 'G-B4KN15ZDJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4irtI4yEC0Z2wIo7eL6Y2uxul1YSixXU',
    appId: '1:449046493777:android:f50f8373c2bf1e0238d670',
    messagingSenderId: '449046493777',
    projectId: 'gestao-software-e052f',
    storageBucket: 'gestao-software-e052f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1JnQfXx7nM1XvKXOowtIuseMoG8obKk',
    appId: '1:449046493777:ios:d445c566ba62d4ec38d670',
    messagingSenderId: '449046493777',
    projectId: 'gestao-software-e052f',
    storageBucket: 'gestao-software-e052f.firebasestorage.app',
    iosBundleId: 'com.example.gestao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1JnQfXx7nM1XvKXOowtIuseMoG8obKk',
    appId: '1:449046493777:ios:d445c566ba62d4ec38d670',
    messagingSenderId: '449046493777',
    projectId: 'gestao-software-e052f',
    storageBucket: 'gestao-software-e052f.firebasestorage.app',
    iosBundleId: 'com.example.gestao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCBgMNq0nWF7YUpVSEmxTTGi7ZQnMJDUQ',
    appId: '1:449046493777:web:459feaafb6ae783638d670',
    messagingSenderId: '449046493777',
    projectId: 'gestao-software-e052f',
    authDomain: 'gestao-software-e052f.firebaseapp.com',
    storageBucket: 'gestao-software-e052f.firebasestorage.app',
    measurementId: 'G-8TWNMP7JGM',
  );
}
